sudo: false
language: java
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true
# Open JDK has limited certificates - see https://www.deps.co/guides/travis-ci-latest-java/
matrix:
  include:
  - jdk: openjdk10
    before_install:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
